name: deployment

on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci
            - name: run lint
              run: npm run lint
    
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps: 
            - name: checkout code
              uses: actions/checkout@v3
            - name: build 
              run: npm build
            - name: run test
              run: npm run test
    
    deploy:
        needs: [lint, test]
        runs-on: ubuntu-latest
        steps:
            - name: checkout code 
              uses: actions/checkout@v3
            - name: deploy
              run: echo"deploying..."